version: '3.8'

services:
  # The backend Node.js service
  server:
    image: jaysisharma/mern-server:latest  
    container_name: mern_server
    restart: unless-stopped
    environment:
      # Pass environment variables to the container.
      # Use a .env file at the root of your project for these values.
      - ATLAS_URI=${ATLAS_URI}
    networks:
      - mern-app-network

  # The frontend React/NGINX service
  client:
    image: jaysisharma/mern-client:latest
    container_name: mern_client
    restart: unless-stopped
    ports:
      # Map port 80 of the host to port 80 of the container.
      # This makes the frontend accessible via the EC2 instance's IP address.
      - "80:80"
    depends_on:
      - server # Ensures the backend starts before the frontend
    networks:
      - mern-app-network

# Define the network that allows containers to communicate with each other.
networks:
  mern-app-network:
    driver: bridge

