version: '3.8'

services:
  # The backend Node.js service
  server:
    build:
      context: ./server
    container_name: mern_server
    restart: unless-stopped
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - PORT=5000
    # No 'ports' section is needed here for the server to be reached by the client.
    # The containers will communicate over the Docker network.
    # Exposing the port is only necessary if you want to access the API directly from the host.
    ports:
      - "5000:5000" # Optional: for direct API testing from your machine
    networks:
      - mern-app-network

  # The frontend React/NGINX service
  client:
    build:
      context: ./client
    container_name: mern_client
    restart: unless-stopped
    ports:
      # Map port 80 of the host to port 80 of the container
      - "80:80"
    depends_on:
      - server
    networks:
      - mern-app-network

networks:
  mern-app-network:
    driver: bridge