version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - mern-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - ATLAS_URI=${ATLAS_URI}  # Load from .env file in root (where docker-compose is run)
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
