version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    environment:
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - mern-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${SERVER_PORT}
      - ATLAS_URI=${ATLAS_URI}
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
