name: MERN App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-server:latest

      - name: Build and Push Client Image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-client:latest

      - name: 🚀 Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔗 Connecting to EC2 instance..."
            echo "➡️ Navigating to app directory..."
            cd /home/ubuntu/
            echo "📂 Current directory contents:"
            ls

            echo "🧹 Removing old Exercise_Tracker directory..."
            rm -rf Exercise_Tracker

            echo "⬇️ Cloning Exercise_Tracker from GitHub..."
            git clone https://github.com/jaysisharma/Exercise_Tracker.git

            echo "📂 Moving into Exercise_Tracker directory..."
            cd Exercise_Tracker

            echo "🔐 Writing .env file with ATLAS_URI..."
            echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" > .env

            echo "🐳 Pulling latest Docker images (if any)..."
            docker-compose pull

            echo "🛠️ Rebuilding and restarting Docker containers..."
            docker-compose up -d --force-recreate

            echo "🧼 Pruning unused Docker images to save space..."
            docker image prune -f

            echo "✅ Deployment completed successfully."

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "CI/CD Bot"
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_COLOR: "good"
          SLACK_TITLE: "Deployment Successful! :white_check_mark:"
          SLACK_MESSAGE: "The latest version of the MERN app has been deployed to production."

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "CI/CD Bot"
          SLACK_ICON_EMOJI: ":x:"
          SLACK_COLOR: "danger"
          SLACK_TITLE: "Deployment Failed! :red_circle:"
          SLACK_MESSAGE: "The deployment failed. Please check the GitHub Actions logs for details."
